export default [
  {
    id: 1,
    title_zh_cn: '财富卡',
    desc_zh_cn: '新的一年里，你的所有努力、好运都会为你带来与之匹配的财富，你会获得不错的offer，还会加薪升职，但这一切，都源自你的自信与付出',
    title_en: 'Fortune',
    desc_en: 'In the new year, all your hard work and good luck will bring you matching wealth, you will get a good offer, and you will get a raise and promotion, but all of this comes from your self-confidence and dedication',
    title_ja: '財源',
    desc_ja: '新年には、あなたのすべての努力と幸運があなたに一致する富をもたらし、あなたは良いオファーを受け取り、そしてあなたは昇進と昇進を得るでしょう、しかしこれはすべてあなたの自信と献身から来ています',
  },
  {
    id: 2,
    title_zh_cn: '学业卡',
    desc_zh_cn: '新的一年里，你会与良师益友为伴，学习路上畅通无阻。如果你已经走出校园，那么你将开拓视野，踏入更新的领域。书山有路勤为径，学海无涯苦作舟。',
    title_en: 'Studies',
    desc_en: 'In the new year, you will be accompanied by mentors and friends, and your learning journey will be unimpeded. If you have already stepped out of campus, then you will broaden your horizons and step into newer areas. There are roads and diligence in the mountain of books, and there is no end to study the sea and work hard.',
    title_ja: '学業',
    desc_ja: '新年には、メンターや友人が同行し、学習の旅が妨げられることはありません。 すでにキャンパスを出た場合は、視野を広げて新しいエリアに足を踏み入れます。 本の山には道と勤勉さがあり、海を研究して一生懸命働くことに終わりはありません。',
  },
  {
    id: 3,
    title_zh_cn: '友情卡',
    desc_zh_cn: '新的一年里，你会遇到更多志同道合的人，还会与多年的好友变得更加亲密。以人为镜，可以明得失，希望你和你的朋友们可以彼此帮助、彼此进步。',
    title_en: 'Friends',
    desc_en: 'In the new year, you will meet more like-minded people, and you will become closer with your friends for many years. With people as a mirror, you can understand gains and losses. I hope you and your friends can help each other and make progress.',
    title_ja: '友情',
    desc_ja: '新年には、志を同じくする人々と出会い、長年友達と親しくなります。 人を鏡にして、利益と損失を理解することができます。あなたとあなたの友人が互いに助け合い、進歩することを願っています。',
  },
  {
    id: 4,
    title_zh_cn: '爱情卡',
    desc_zh_cn: '新的一年里，你会遇见自己的心上人，他/她也许已经在你的身边，也许还在人海中等待你的邂逅，但肯定的是，你爱的和爱你的人终究不会被辜负。',
    title_en: 'Romance',
    desc_en: 'In the new year, you will meet your sweetheart. He/she may already be by your side, or may still be waiting for you Let down.',
    title_ja: '愛',
    desc_ja: '新年には、恋人に会うでしょう。恋人はすでにあなたのそばにいるか、まだあなたを待っているかもしれません。',
  },
  {
    id: 5,
    title_zh_cn: '事业卡',
    desc_zh_cn: '新的一年里，你的事业会步步飞升，水涨船高。无论你正在寻求offer、或从业、或创业，要相信明天一定会更好，明天的你会比今天更优秀！',
    title_en: 'Cause',
    desc_en: 'In the new year, your career will rise step by step and the tide will rise. Whether you are seeking an offer, or working in a business, or starting a business, you must believe that tomorrow will be better, and you will be better tomorrow than today!',
    title_ja: '事業',
    desc_ja: '新年には、あなたのキャリアは段階的に上昇し、潮流は上昇します。 あなたが申し出を求めているか、ビジネスで働いているか、またはビジネスを始めているかどうかにかかわらず、あなたは明日がより良くなると信じなければなりません、そしてあなたは今日より良くなるでしょう！',
  },
  {
    id: 6,
    title_zh_cn: '好运卡',
    desc_zh_cn: '新的一年里，你的事业会步步飞升，水涨船高。无论你正在寻求offer、或从业、或创业，要相信明天一定会更好，明天的你会比今天更优秀！',
    title_en: 'Luck',
    desc_en: 'In the new year, your career will rise step by step and the tide will rise. Whether you are seeking an offer, or working in a business, or starting a business, you must believe that tomorrow will be better, and you will be better tomorrow than today!',
    title_ja: 'ラック',
    desc_ja: '新年には、あなたのキャリアは段階的に上昇し、潮流は上昇します。 あなたが申し出を求めているか、ビジネスで働いているか、またはビジネスを始めているかどうかにかかわらず、あなたは明日がより良くなると信じなければなりません、そしてあなたは今日より良くなるでしょう！',
  },
]
